preferSymlinkedExecutables: true
shellEmulator: true
trustPolicy: no-downgrade
linkWorkspacePackages: true
injectWorkspacePackages: true

trustPolicyExclude:
    - chokidar@4.0.3
    - semver@6.3.1

packages:
    - apps/**/*
    - packages/**/*
    - tools/**/*

allowBuilds:
    esbuild: true
    unrs-resolver: true

overrides:
    typescript: 6.0.3
