//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "loans")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub profile_id: Uuid,
    pub account_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub direction: String,
    #[sea_orm(column_type = "Text")]
    pub schedule_type: String,
    pub name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub principal_amount: String,
    pub currency_code: String,
    #[sea_orm(column_type = "Text")]
    pub annual_effective_rate: String,
    pub term_months: i64,
    pub installments_count: i64,
    #[sea_orm(column_type = "Text")]
    pub installment_amount: String,
    #[sea_orm(column_type = "Text")]
    pub total_amount_with_interest: String,
    pub start_date: DateTime,
    pub first_payment_date: DateTime,
    pub due_date: DateTime,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Accounts,
    #[sea_orm(has_many = "super::loan_payments::Entity")]
    LoanPayments,
    #[sea_orm(has_one = "super::loan_schedule_custom::Entity")]
    LoanScheduleCustom,
    #[sea_orm(has_one = "super::loan_schedule_daily::Entity")]
    LoanScheduleDaily,
    #[sea_orm(has_one = "super::loan_schedule_periodic::Entity")]
    LoanSchedulePeriodic,
    #[sea_orm(has_one = "super::loan_schedule_weekly::Entity")]
    LoanScheduleWeekly,
    #[sea_orm(
        belongs_to = "super::profiles::Entity",
        from = "Column::ProfileId",
        to = "super::profiles::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Profiles,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::loan_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanPayments.def()
    }
}

impl Related<super::loan_schedule_custom::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanScheduleCustom.def()
    }
}

impl Related<super::loan_schedule_daily::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanScheduleDaily.def()
    }
}

impl Related<super::loan_schedule_periodic::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanSchedulePeriodic.def()
    }
}

impl Related<super::loan_schedule_weekly::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanScheduleWeekly.def()
    }
}

impl Related<super::profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Profiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
