//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "loan_payments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub loan_id: Uuid,
    pub transaction_id: Uuid,
    pub principal_amount: String,
    pub interest_amount: String,
    pub late_fee_amount: String,
    pub total_amount: String,
    pub payment_date: DateTime,
    pub notes: Option<String>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::loans::Entity",
        from = "Column::LoanId",
        to = "super::loans::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Loans,
    #[sea_orm(
        belongs_to = "super::transactions::Entity",
        from = "Column::TransactionId",
        to = "super::transactions::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Transactions,
}

impl Related<super::loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Loans.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
