//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod accounts;
pub mod categories;
pub mod credit_transaction_details;
pub mod device_profile_sessions;
pub mod loan_payments;
pub mod loan_schedule_custom;
pub mod loan_schedule_daily;
pub mod loan_schedule_periodic;
pub mod loan_schedule_weekly;
pub mod loans;
pub mod payment_method_config;
pub mod payment_methods;
pub mod profiles;
pub mod service_fee_fixed;
pub mod service_fee_percentage;
pub mod service_fees;
pub mod transactions;
