//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "payment_method_config")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub payment_method_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub credit_limit: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub interest_rate: Option<String>,
    pub billing_cycle_day: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::PaymentMethodId",
        to = "super::payment_methods::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PaymentMethods,
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
