//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "service_fees")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub account_id: Option<Uuid>,
    pub payment_method_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub threshold_amount: Option<String>,
    pub is_active: bool,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Accounts,
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::PaymentMethodId",
        to = "super::payment_methods::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PaymentMethods,
    #[sea_orm(has_one = "super::service_fee_fixed::Entity")]
    ServiceFeeFixed,
    #[sea_orm(has_one = "super::service_fee_percentage::Entity")]
    ServiceFeePercentage,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl Related<super::service_fee_fixed::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServiceFeeFixed.def()
    }
}

impl Related<super::service_fee_percentage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServiceFeePercentage.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
