//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "service_fee_percentage")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub service_fee_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub percentage: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub min_amount: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub max_amount: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::service_fees::Entity",
        from = "Column::ServiceFeeId",
        to = "super::service_fees::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ServiceFees,
}

impl Related<super::service_fees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServiceFees.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
